// <auto-generated />
using System;
using AlwahaLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlwahaLibrary.Data.Migrations
{
    [DbContext(typeof(AlwahaDbContext))]
    [Migration("20251006192353_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AlwahaLibrary.Models.AnalyticsEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int?>("ScreenHeight")
                        .HasColumnType("int");

                    b.Property<int?>("ScreenWidth")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AnalyticsEvents");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.AuditEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AuditAction")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.BundleItem", b =>
                {
                    b.Property<string>("BundleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemTypeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BundleId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("BundleItems");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.CloudflareAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgOriginResponseTime")
                        .HasColumnType("double");

                    b.Property<long>("BandwidthCached")
                        .HasColumnType("bigint");

                    b.Property<long>("BandwidthTotal")
                        .HasColumnType("bigint");

                    b.Property<long>("BandwidthUncached")
                        .HasColumnType("bigint");

                    b.Property<double>("CacheHitRate")
                        .HasColumnType("double");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("PageViews")
                        .HasColumnType("bigint");

                    b.Property<long>("Requests")
                        .HasColumnType("bigint");

                    b.Property<long>("Status2xx")
                        .HasColumnType("bigint");

                    b.Property<long>("Status3xx")
                        .HasColumnType("bigint");

                    b.Property<long>("Status4xx")
                        .HasColumnType("bigint");

                    b.Property<long>("Status5xx")
                        .HasColumnType("bigint");

                    b.Property<long>("ThreatsBlocked")
                        .HasColumnType("bigint");

                    b.Property<long>("UniqueVisitors")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CloudflareAnalytics");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.ItemTag", b =>
                {
                    b.Property<string>("TagId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TagId");

                    b.ToTable("ItemTags");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.ItemToSet", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SetId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ItemId", "SetId");

                    b.HasIndex("SetId");

                    b.ToTable("ItemToSets");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.ItemToTag", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TagId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ItemToTags");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.ItemType", b =>
                {
                    b.Property<string>("ItemTypeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Colour")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ItemTypeId");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.MenuItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Colour")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSet")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemTypeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("RestoredBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RestoredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.BundleItem", b =>
                {
                    b.HasOne("AlwahaLibrary.Models.ItemType", "ItemType")
                        .WithMany("BundleItems")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.ItemToSet", b =>
                {
                    b.HasOne("AlwahaLibrary.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlwahaLibrary.Models.MenuItem", "MenuSet")
                        .WithMany("ItemsToSets")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("MenuSet");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.ItemToTag", b =>
                {
                    b.HasOne("AlwahaLibrary.Models.MenuItem", "MenuItem")
                        .WithMany("ItemsToTags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlwahaLibrary.Models.ItemTag", "ItemTag")
                        .WithMany("ItemsToTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemTag");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.MenuItem", b =>
                {
                    b.HasOne("AlwahaLibrary.Models.ItemType", "ItemType")
                        .WithMany("MenuItems")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.ItemTag", b =>
                {
                    b.Navigation("ItemsToTags");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.ItemType", b =>
                {
                    b.Navigation("BundleItems");

                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("AlwahaLibrary.Models.MenuItem", b =>
                {
                    b.Navigation("ItemsToSets");

                    b.Navigation("ItemsToTags");
                });
#pragma warning restore 612, 618
        }
    }
}
